version: '2'
services:
    boyuanstore-app:
        image: boyuanstore
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://boyuanstore-mysql:3306/boyuanstore?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    boyuanstore-mysql:
        extends:
            file: mysql.yml
            service: boyuanstore-mysql
